name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t arnoldabraham/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true arnoldabraham/react-test npm test
 
      - run: docker build -t arnoldabraham/multi-client ./client
      - run: docker build -t arnoldabraham/multi-nginx ./nginx
      - run: docker build -t arnoldabraham/multi-server ./server
      - run: docker build -t arnoldabraham/multi-worker ./worker

      - run: docker push arnoldabraham/multi-client
      - run: docker push arnoldabraham/multi-nginx
      - run: docker push arnoldabraham/multi-server
      - run: docker push arnoldabraham/multi-worker
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: MultiDocker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-875214969113
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip